### PR TITLE
Refactor + Docs + API cleanup + CSV

### PR DESCRIPTION
**Pull request by gampleman**
Sorry for the massive PR that does way too much. I sort of ended up doing all of these things interleaved and disentangling the changes would have been rather painful.

Let me summarize what's going on here:

#### Refactor

Some elm-review fixes, but mostly I changed the CodeGenerator logic to enable it to compute on some arbitrary input. This was needed for CSVs (since it's a flat format we need to know by the time we call `Decode.field` the complete path, not just the field name). However I have further plans for this feature, such as accepting user input or potentially processing two types at a time, etc.

Also I extracted two new modules:

- `Internal.CodeGenerationResult` deals with what used to be `Result String (Expression, List Function, List (String, Expression))` in `Internal.CodeGenerator`. Now the triple is a proper record and a lot of the weird functions (remember `transmogrify`?) dealing with this datatype have been moved to its module and named something slightly more sensible.
- `Internal.Postprocess` deals with post processing ASTs. This was scattered between `Internal.CodeGenerator` and `Internal.Helpers`, neither of which are ideal. 

Also install core-extra, which allows us to get rid of a good few functions from `Internal.Helpers`.

#### Docs

I updated the README and generally reviewed the docs so we can actually publish this.

#### API cleanup

I changed my mind and made it not a drop-in replacement for elm-review-no-debug. The way to use these is different enough and also I think this codebase is complicated enough that it should focus on its core idea and not also do other things.

I also got rid of the idea of `amend`. It seems a bit preemptively designed.

#### CSV Decoder

Just another generator.

### Publish or perish?

Should we actually publish this thing? I can draft a release announcement. I'd position it as a beta, since there's definitely a lot of space for improvement, but its becoming useful enough that making it more widely publicized would make sense.

### CODE REVIEW

**Comment by MartinSStewart** [comment]
You've put in much more work than I have at this point. If you think this is a good time to publish the package then lets do it. 😃  

I haven't had time or motivation to work on this in a while, so if you'd like I can transfer the repo to you if you'd like to publish it under your name.

Haven't had time to review the whole PR either but I trust your judgement. 👍

**Comment by gampleman** [comment]
:shrug: either way. 

If you're more comfortable transferring it, than I'd be happy to accept. I can add a section to the readme that gives you credit for the original idea/implementation. 

If not, than we can just continue as is.

**Comment by MartinSStewart** [comment]
I tried transferring it but it isn't possible while you have a forked copy.

**Comment by gampleman** [comment]
OK, I'll delete my fork.

**Pull request merged**
